spring:
  profiles:
    active: dev
  application:
    name: account-service

  datasource:
    url: ${ACCOUNT_DATASOURCE_URL}
    username: ${ACCOUNT_DATASOURCE_USERNAME}
    password: ${ACCOUNT_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

staffjoy:
  common:
    deploy-env: ${DEPLOY:V2}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service:8080}
  signing-secret: ${SIGNING_SECRET}
