spring:
  profiles:
    active: dev
  application:
    name: account-service

  datasource:
    url: ${ACCOUNT_DATASOURCE_URL}
    username: ${ACCOUNT_DATASOURCE_USERNAME}
    password: ${ACCOUNT_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
