spring:
  profiles:
    active: dev
  application:
    name: staffjoy-auth


staffjoy:
  common:
    permitUrls:
      - /register
      - /activate
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-servie:8080}